# Generated by Django 5.1.3 on 2024-11-22 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/generated/')),
                ('imputation_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Use [% N %] to embed images or [% GEN_N %] for generated images.')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_image', to='FinalProject.imagegenerated')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='FinalProject.image')),
            ],
        ),
        migrations.CreateModel(
            name='PaperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.image')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.paper')),
            ],
            options={
                'unique_together': {('paper', 'order')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='papers', through='FinalProject.PaperImage', to='FinalProject.image'),
        ),
        migrations.CreateModel(
            name='PaperWithGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.imagegenerated')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.paper')),
            ],
            options={
                'unique_together': {('paper', 'order')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='generated_images',
            field=models.ManyToManyField(blank=True, related_name='papers', through='FinalProject.PaperWithGeneratedImage', to='FinalProject.imagegenerated'),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('university', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperWithResearcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.paper')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.researcher')),
            ],
        ),
        migrations.AddField(
            model_name='imagegenerated',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='FinalProject.researcher'),
        ),
        migrations.AddField(
            model_name='image',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.researcher'),
        ),
    ]
