# Generated by Django 5.1.3 on 2024-12-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0003_remove_corruptedimage_corrupted_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corruptedimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='corruptedimage',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='corruptedimage',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='mask',
            name='original_image',
        ),
        migrations.AddField(
            model_name='corruptedimage',
            name='corrupted_file',
            field=models.ImageField(default=1, upload_to='corrupted_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='corrupted_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrupted_images', to='FinalProject.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masked_images', to='FinalProject.image'),
        ),
        migrations.AddField(
            model_name='mask',
            name='mask_file',
            field=models.ImageField(default=1, upload_to='masks/'),
            preserve_default=False,
        ),
    ]
