# Generated by Django 5.1.3 on 2024-12-07 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0005_alter_image_corrupted_image_alter_image_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FinalProject.researcher'),
        ),
    ]
