# Generated by Django 5.1.3 on 2024-12-07 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0006_alter_image_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=models.TextField(help_text='Use [% N %] to embed images, [% GEN_N %] for generated images, [% MASK_N %] for masks, or [% CORR_N %] for corrupted images.'),
        ),
        migrations.CreateModel(
            name='PaperWithCorruptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.corruptedimage')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.paper')),
            ],
            options={
                'unique_together': {('paper', 'order')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='corrupted_images',
            field=models.ManyToManyField(blank=True, related_name='papers', through='FinalProject.PaperWithCorruptedImage', to='FinalProject.corruptedimage'),
        ),
        migrations.CreateModel(
            name='PaperWithMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('mask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.mask')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.paper')),
            ],
            options={
                'unique_together': {('paper', 'order')},
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='masks',
            field=models.ManyToManyField(blank=True, related_name='papers', through='FinalProject.PaperWithMask', to='FinalProject.mask'),
        ),
    ]
