# Generated by Django 5.1.3 on 2024-12-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0007_alter_paper_content_paperwithcorruptedimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperwithcorruptedimage',
            old_name='image',
            new_name='corrupted_image',
        ),
        migrations.RenameField(
            model_name='paperwithgeneratedimage',
            old_name='image',
            new_name='generated_image',
        ),
    ]
