# Generated by Django 5.1.3 on 2024-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0008_rename_image_paperwithcorruptedimage_corrupted_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegenerated',
            name='imputation_method',
        ),
        migrations.RemoveField(
            model_name='imagegenerated',
            name='researcher',
        ),
        migrations.AddField(
            model_name='imagegenerated',
            name='psnr_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagegenerated',
            name='ssim_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegenerated',
            name='image_file',
            field=models.ImageField(upload_to='generated_images/'),
        ),
    ]
