# Generated by Django 5.1.3 on 2024-12-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0012_alter_image_researcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegenerated',
            name='image_file',
        ),
        migrations.AddField(
            model_name='imagegenerated',
            name='image',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images_by_image', to='FinalProject.image'),
            preserve_default=False,
        ),
    ]
