# Generated by Django 5.1.1 on 2024-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_v20state_alter_voter_v21primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='PrecinctNumber',
            field=models.TextField(),
        ),
    ]
