# Generated by Django 5.1.1 on 2024-10-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
